# fly.toml app configuration file generated for project-members-only on 2023-12-22T10:43:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "project-members-only"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
